data_dir: "/usr0/home/gis/data/tacred/data/json"
vocab_dir: "/usr0/home/gis/data/tacred/data/vocab"
emb_dim: 300
ner_dim: 30
pos_dim': 30
hidden_dim: 200
num_layers: 2
input_dropout: 0.5
gcn_dropout: 0.5
word_dropout: 0.04
topn: 1e10
lower: False
test_save_dir: '/usr0/home/gis/research/tacred-exploration/tacred_test_performances'
prune_k: 1
conv_l2: 0
pooling: 'max'
pooling_l2: 0.003
mlp_layers: 2
no_adj: False
rnn: True
rnn_hidden: 200
rnn_layers: 1
rnn_dropout: 0.5
lr: .3
lr_decay: 0.9
decay_epoch: 5
optim: 'sgd'
num_epoch: 100
batch_size: 50
max_grad_norm: 5.0
log_step: 20
log: 'logs.txt'
save_epoch: 100
save_dir: '/usr0/home/gis/research/tacred-exploration/saved_models'
id: baseline-CGCN-2
info: ''
test_confusion_save_file: ''
seed: 1234
cuda: torch.cuda.is_available()
cpu: False
load: False
model_file: ''